<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:grunnundersokelserutvidet="https://skjema.geonorge.no/SOSI/produktspesifikasjon/nasjonal-database-for-grunnundersokelser-nadag/grunnundersokelser-utvidet/1.0" elementFormDefault="qualified" targetNamespace="https://skjema.geonorge.no/SOSI/produktspesifikasjon/nasjonal-database-for-grunnundersokelser-nadag/grunnundersokelser-utvidet/1.0" version="1.0">
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <simpleType name="BorlengdeKvalitetType">
    <restriction base="string">
      <enumeration value="1"/>
      <enumeration value="2"/>
    </restriction>
  </simpleType>
  <element name="BorlengdeTilBerg" substitutionGroup="gml:AbstractObject" type="grunnundersokelserutvidet:BorlengdeTilBergType"/>
  <complexType name="BorlengdeTilBergType">
    <sequence>
      <element minOccurs="0" name="borlengdeKvalitet" type="grunnundersokelserutvidet:BorlengdeKvalitetType">
        <annotation>
          <documentation>Beskriver om dybden til berg er antatt eller påvist med en sikker metode&lt;br/&gt;&lt;engelsk style="font-style:italic;font-size:smaller"&gt; &lt;br/&gt;Defines the quality of the depth information either assumed or confirmed by a secure method&lt;br/&gt;&lt;/engelsk&gt;</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="borlengdeTilBerg" type="double">
        <annotation>
          <documentation>Dybde til fjell som ikke er målt men basert på tolkning [m]&lt;br/&gt;&lt;engelsk style="font-style:italic;font-size:smaller"&gt;&lt;br/&gt;Depth to bedrock based on interpretation
&lt;/engelsk&gt;</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="BorlengdeTilBergPropertyType">
    <sequence>
      <element ref="grunnundersokelserutvidet:BorlengdeTilBerg"/>
    </sequence>
  </complexType>
  <simpleType name="DokumentTypeType">
    <restriction base="string">
      <enumeration value="AssessmentReport"/>
      <enumeration value="BoreHoleAttachment"/>
      <enumeration value="DigitizedDwg"/>
      <enumeration value="DigitizedImage"/>
      <enumeration value="Drawing"/>
      <enumeration value="GeoReport"/>
      <enumeration value="Image"/>
      <enumeration value="LabReport"/>
      <enumeration value="Model"/>
      <enumeration value="NotSpecified"/>
      <enumeration value="PlanPdf"/>
      <enumeration value="PlanSymbolImage"/>
      <enumeration value="ProfileImage"/>
      <enumeration value="ProfilePdf"/>
      <enumeration value="RawdataFile"/>
    </restriction>
  </simpleType>
  <element name="EksternIdentifikasjon" substitutionGroup="gml:AbstractObject" type="grunnundersokelserutvidet:EksternIdentifikasjonType"/>
  <complexType name="EksternIdentifikasjonType">
    <sequence>
      <element minOccurs="0" name="eksternId" type="string">
        <annotation>
          <documentation>Lokal identifikator, tildelt av ekstern leverendør. &lt;br/&gt;Det er data leverendørens ansvar å sørge for at denne eksterne identifikatoren er unik innenfor navnerommet.</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="eksternNavnerom" type="string">
        <annotation>
          <documentation>Navnerom som identifiserer datakilden/leverandør til objektet</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="eksternVersjonId" type="string">
        <annotation>
          <documentation>Identifikasjon av en spesiell versjon av et geografisk objekt  Dersom spesifikasjonen av et geografisk objekt med en identifikasjon inkludererer livsløpssyklusinformasjon, benyttes denne versjonId for å skille mellom ulike versjoner av samme objekt. versjonId er en unik  identifikasjon av versjonen.</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="eksternLeveringDato" type="dateTime">
        <annotation>
          <documentation>Når objektet ble levert til database (Nadag)</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="EksternIdentifikasjonPropertyType">
    <sequence>
      <element ref="grunnundersokelserutvidet:EksternIdentifikasjon"/>
    </sequence>
  </complexType>
  <simpleType name="FeltundersTypeType">
    <restriction base="string">
      <enumeration value="10"/>
      <enumeration value="20"/>
      <enumeration value="30"/>
    </restriction>
  </simpleType>
  <simpleType name="GeotekniskFeltUndersMetodeType">
    <restriction base="string">
      <enumeration value="21"/>
      <enumeration value="42"/>
      <enumeration value="54"/>
      <enumeration value="55"/>
      <enumeration value="56"/>
      <enumeration value="57"/>
      <enumeration value="58"/>
      <enumeration value="61"/>
      <enumeration value="63"/>
    </restriction>
  </simpleType>
  <simpleType name="GeotekniskMetodeType">
    <restriction base="string">
      <enumeration value="1"/>
      <enumeration value="10"/>
      <enumeration value="11"/>
      <enumeration value="12"/>
      <enumeration value="13"/>
      <enumeration value="14"/>
      <enumeration value="15"/>
      <enumeration value="16"/>
      <enumeration value="17"/>
      <enumeration value="18"/>
      <enumeration value="19"/>
      <enumeration value="2"/>
      <enumeration value="20"/>
      <enumeration value="21"/>
      <enumeration value="22"/>
      <enumeration value="23"/>
      <enumeration value="24"/>
      <enumeration value="25"/>
      <enumeration value="26"/>
      <enumeration value="27"/>
      <enumeration value="28"/>
      <enumeration value="29"/>
      <enumeration value="3"/>
      <enumeration value="30"/>
      <enumeration value="31"/>
      <enumeration value="32"/>
      <enumeration value="33"/>
      <enumeration value="34"/>
      <enumeration value="35"/>
      <enumeration value="36"/>
      <enumeration value="37"/>
      <enumeration value="38"/>
      <enumeration value="39"/>
      <enumeration value="4"/>
      <enumeration value="40"/>
      <enumeration value="41"/>
      <enumeration value="42"/>
      <enumeration value="43"/>
      <enumeration value="44"/>
      <enumeration value="45"/>
      <enumeration value="46"/>
      <enumeration value="47"/>
      <enumeration value="48"/>
      <enumeration value="49"/>
      <enumeration value="5"/>
      <enumeration value="50"/>
      <enumeration value="51"/>
      <enumeration value="6"/>
      <enumeration value="7"/>
      <enumeration value="8"/>
      <enumeration value="9"/>
    </restriction>
  </simpleType>
  <simpleType name="GrunnvannAkviferType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="1"/>
      <enumeration value="2"/>
      <enumeration value="3"/>
      <enumeration value="4"/>
    </restriction>
  </simpleType>
  <simpleType name="GrunnvannObservasjonKodeType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="1"/>
      <enumeration value="2"/>
      <enumeration value="3"/>
      <enumeration value="4"/>
      <enumeration value="5"/>
      <enumeration value="6"/>
      <enumeration value="7"/>
      <enumeration value="8"/>
      <enumeration value="9"/>
    </restriction>
  </simpleType>
  <simpleType name="HovedLagKlassifiseringsKodeType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="1"/>
      <enumeration value="10"/>
      <enumeration value="11"/>
      <enumeration value="12"/>
      <enumeration value="13"/>
      <enumeration value="14"/>
      <enumeration value="15"/>
      <enumeration value="16"/>
      <enumeration value="17"/>
      <enumeration value="18"/>
      <enumeration value="19"/>
      <enumeration value="2"/>
      <enumeration value="20"/>
      <enumeration value="21"/>
      <enumeration value="22"/>
      <enumeration value="23"/>
      <enumeration value="24"/>
      <enumeration value="25"/>
      <enumeration value="26"/>
      <enumeration value="27"/>
      <enumeration value="28"/>
      <enumeration value="29"/>
      <enumeration value="3"/>
      <enumeration value="30"/>
      <enumeration value="31"/>
      <enumeration value="32"/>
      <enumeration value="33"/>
      <enumeration value="34"/>
      <enumeration value="35"/>
      <enumeration value="36"/>
      <enumeration value="37"/>
      <enumeration value="38"/>
      <enumeration value="39"/>
      <enumeration value="4"/>
      <enumeration value="40"/>
      <enumeration value="5"/>
      <enumeration value="6"/>
      <enumeration value="7"/>
      <enumeration value="8"/>
      <enumeration value="9"/>
    </restriction>
  </simpleType>
  <simpleType name="HøydeReferanseType">
    <restriction base="string">
      <enumeration value="5776"/>
      <enumeration value="5941"/>
      <enumeration value="Ukjent"/>
    </restriction>
  </simpleType>
  <element name="Identifikasjon" substitutionGroup="gml:AbstractObject" type="grunnundersokelserutvidet:IdentifikasjonType"/>
  <complexType name="IdentifikasjonType">
    <sequence>
      <element minOccurs="0" name="lokalId" type="string">
        <annotation>
          <documentation>Lokal identifikator, tildelt av dataleverendør/dataforvalter. Den lokale identifikatoren er unik innenfor navnerommet, ingen andre objekter har samme identifikator.&lt;br/&gt;NOTE: Det er data leverendørens ansvar å sørge for at denne lokale identifikatoren er unik innenfor navnerommet.</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="navnerom" type="string">
        <annotation>
          <documentation>Navnerom som unikt identifiserer datakilden til objektet, starter med to bokstavs kode jfr ISO 3166. Benytter understreking  ("_") dersom data produsenten ikke er assosiert med bare et land.
&lt;br/&gt;NOTE 1 : Verdien for nanverom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og vil registreres i "INSPIRE external  Object Identifier Namespaces Register"&lt;br/&gt;Eksempel: NO for Norge.</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="versjonId" type="string">
        <annotation>
          <documentation>Identifikasjon av en spesiell versjon av et geografisk objekt (instans), maksimum lengde på 25 karakterers. Dersom spesifikasjonen av et geografisk objekt med en identifikasjon inkludererer livsløpssyklusinformasjon, benyttes denne versjonId for å skille mellom ulike versjoner av samme objekt. versjonId er en unik  identifikasjon av versjonen. &lt;br/&gt;NOTE Maksimum lengde er valgt for å tillate tidsregistrering i henhold til  ISO 8601, slik som  "2007-02-12T12:12:12+05:30" som versjonId.</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="IdentifikasjonPropertyType">
    <sequence>
      <element ref="grunnundersokelserutvidet:Identifikasjon"/>
    </sequence>
  </complexType>
  <simpleType name="KlassifiseringMetodeType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="1"/>
      <enumeration value="2"/>
      <enumeration value="3"/>
      <enumeration value="4"/>
      <enumeration value="5"/>
      <enumeration value="6"/>
      <enumeration value="7"/>
      <enumeration value="8"/>
    </restriction>
  </simpleType>
  <simpleType name="KvikkleirePåvisningType">
    <restriction base="string">
      <enumeration value="Antatt"/>
      <enumeration value="AntattIkkeKvikk"/>
      <enumeration value="IkkeVurdert"/>
      <enumeration value="Sikker"/>
      <enumeration value="Usikker"/>
    </restriction>
  </simpleType>
  <simpleType name="LagPosisjonType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="1"/>
      <enumeration value="2"/>
      <enumeration value="3"/>
    </restriction>
  </simpleType>
  <element name="Link" substitutionGroup="gml:AbstractObject" type="grunnundersokelserutvidet:LinkType"/>
  <complexType name="LinkType">
    <sequence>
      <element minOccurs="0" name="href"/>
      <element minOccurs="0" name="rel" type="string"/>
      <element minOccurs="0" name="type" type="string"/>
      <element minOccurs="0" name="title" type="string">
        <annotation>
          <documentation>tilhørerGB &gt; GeotekniskBorehull-title</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="LinkPropertyType">
    <sequence>
      <element ref="grunnundersokelserutvidet:Link"/>
    </sequence>
  </complexType>
  <simpleType name="MålemetodeType">
    <restriction base="string">
      <enumeration value="10"/>
      <enumeration value="11"/>
      <enumeration value="12"/>
      <enumeration value="13"/>
      <enumeration value="14"/>
      <enumeration value="15"/>
      <enumeration value="18"/>
      <enumeration value="19"/>
      <enumeration value="20"/>
      <enumeration value="21"/>
      <enumeration value="22"/>
      <enumeration value="23"/>
      <enumeration value="24"/>
      <enumeration value="30"/>
      <enumeration value="31"/>
      <enumeration value="32"/>
      <enumeration value="33"/>
      <enumeration value="34"/>
      <enumeration value="35"/>
      <enumeration value="36"/>
      <enumeration value="40"/>
      <enumeration value="41"/>
      <enumeration value="42"/>
      <enumeration value="43"/>
      <enumeration value="44"/>
      <enumeration value="45"/>
      <enumeration value="46"/>
      <enumeration value="50"/>
      <enumeration value="51"/>
      <enumeration value="52"/>
      <enumeration value="53"/>
      <enumeration value="54"/>
      <enumeration value="55"/>
      <enumeration value="56"/>
      <enumeration value="60"/>
      <enumeration value="61"/>
      <enumeration value="62"/>
      <enumeration value="63"/>
      <enumeration value="64"/>
      <enumeration value="65"/>
      <enumeration value="66"/>
      <enumeration value="67"/>
      <enumeration value="68"/>
      <enumeration value="69"/>
      <enumeration value="70"/>
      <enumeration value="71"/>
      <enumeration value="72"/>
      <enumeration value="73"/>
      <enumeration value="74"/>
      <enumeration value="77"/>
      <enumeration value="78"/>
      <enumeration value="79"/>
      <enumeration value="80"/>
      <enumeration value="81"/>
      <enumeration value="82"/>
      <enumeration value="90"/>
      <enumeration value="91"/>
      <enumeration value="92"/>
      <enumeration value="93"/>
      <enumeration value="94"/>
      <enumeration value="95"/>
      <enumeration value="96"/>
      <enumeration value="97"/>
      <enumeration value="99"/>
    </restriction>
  </simpleType>
  <simpleType name="MålemetodeHøydeType">
    <restriction base="string">
      <enumeration value="10"/>
      <enumeration value="11"/>
      <enumeration value="12"/>
      <enumeration value="13"/>
      <enumeration value="14"/>
      <enumeration value="15"/>
      <enumeration value="18"/>
      <enumeration value="19"/>
      <enumeration value="20"/>
      <enumeration value="21"/>
      <enumeration value="22"/>
      <enumeration value="23"/>
      <enumeration value="24"/>
      <enumeration value="36"/>
      <enumeration value="60"/>
      <enumeration value="61"/>
      <enumeration value="62"/>
      <enumeration value="63"/>
      <enumeration value="64"/>
      <enumeration value="66"/>
      <enumeration value="67"/>
      <enumeration value="68"/>
      <enumeration value="69"/>
      <enumeration value="70"/>
      <enumeration value="74"/>
      <enumeration value="78"/>
      <enumeration value="79"/>
      <enumeration value="90"/>
      <enumeration value="91"/>
      <enumeration value="92"/>
      <enumeration value="93"/>
      <enumeration value="94"/>
      <enumeration value="95"/>
      <enumeration value="96"/>
      <enumeration value="99"/>
    </restriction>
  </simpleType>
  <simpleType name="NedpressingsKapasitetType">
    <restriction base="string">
      <enumeration value="10"/>
      <enumeration value="100"/>
      <enumeration value="50"/>
    </restriction>
  </simpleType>
  <simpleType name="ObservasjonKodeType">
    <restriction base="string">
      <enumeration value="1"/>
      <enumeration value="10"/>
      <enumeration value="11"/>
      <enumeration value="12"/>
      <enumeration value="13"/>
      <enumeration value="14"/>
      <enumeration value="15"/>
      <enumeration value="16"/>
      <enumeration value="17"/>
      <enumeration value="18"/>
      <enumeration value="19"/>
      <enumeration value="2"/>
      <enumeration value="20"/>
      <enumeration value="21"/>
      <enumeration value="22"/>
      <enumeration value="23"/>
      <enumeration value="24"/>
      <enumeration value="25"/>
      <enumeration value="26"/>
      <enumeration value="27"/>
      <enumeration value="28"/>
      <enumeration value="29"/>
      <enumeration value="3"/>
      <enumeration value="30"/>
      <enumeration value="31"/>
      <enumeration value="32"/>
      <enumeration value="36"/>
      <enumeration value="37"/>
      <enumeration value="38"/>
      <enumeration value="39"/>
      <enumeration value="4"/>
      <enumeration value="41"/>
      <enumeration value="42"/>
      <enumeration value="43"/>
      <enumeration value="44"/>
      <enumeration value="46"/>
      <enumeration value="47"/>
      <enumeration value="48"/>
      <enumeration value="49"/>
      <enumeration value="5"/>
      <enumeration value="50"/>
      <enumeration value="51"/>
      <enumeration value="52"/>
      <enumeration value="53"/>
      <enumeration value="54"/>
      <enumeration value="55"/>
      <enumeration value="56"/>
      <enumeration value="57"/>
      <enumeration value="58"/>
      <enumeration value="59"/>
      <enumeration value="6"/>
      <enumeration value="60"/>
      <enumeration value="61"/>
      <enumeration value="62"/>
      <enumeration value="63"/>
      <enumeration value="64"/>
      <enumeration value="65"/>
      <enumeration value="66"/>
      <enumeration value="7"/>
      <enumeration value="8"/>
      <enumeration value="9"/>
    </restriction>
  </simpleType>
  <element name="PosisjonskvalitetNADAG" substitutionGroup="gml:AbstractObject" type="grunnundersokelserutvidet:PosisjonskvalitetNADAGType"/>
  <complexType name="PosisjonskvalitetNADAGType">
    <sequence>
      <element minOccurs="0" name="målemetode" type="grunnundersokelserutvidet:MålemetodeType">
        <annotation>
          <documentation>Metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="målemetodeHøyde" type="grunnundersokelserutvidet:MålemetodeHøydeType">
        <annotation>
          <documentation>Metode for å måle høyden</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="nøyaktighet" type="integer">
        <annotation>
          <documentation>Punktstandardavviket i grunnriss for punkter samt tverravvik for linjer&lt;br/&gt;Merknad:&lt;br/&gt;Oppgitt i [cm]</documentation>
        </annotation>
      </element>
      <element minOccurs="0" name="nøyaktighetHøyde" type="integer">
        <annotation>
          <documentation>Nøyaktighet for høyden i [cm]</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="PosisjonskvalitetNADAGPropertyType">
    <sequence>
      <element ref="grunnundersokelserutvidet:PosisjonskvalitetNADAG"/>
    </sequence>
  </complexType>
  <simpleType name="PrøvetypeType">
    <restriction base="string">
      <enumeration value="1"/>
      <enumeration value="2"/>
      <enumeration value="3"/>
      <enumeration value="4"/>
      <enumeration value="5"/>
      <enumeration value="6"/>
    </restriction>
  </simpleType>
  <simpleType name="RepresentasjonKvalitetType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="10"/>
      <enumeration value="20"/>
      <enumeration value="30"/>
      <enumeration value="40"/>
      <enumeration value="42"/>
      <enumeration value="45"/>
      <enumeration value="50"/>
    </restriction>
  </simpleType>
  <simpleType name="SondeKvalitetKlasseType">
    <restriction base="string">
      <enumeration value="1"/>
      <enumeration value="2"/>
      <enumeration value="3"/>
      <enumeration value="4"/>
    </restriction>
  </simpleType>
  <simpleType name="StoppKodeType">
    <restriction base="string">
      <enumeration value="0"/>
      <enumeration value="88"/>
      <enumeration value="89"/>
      <enumeration value="90"/>
      <enumeration value="91"/>
      <enumeration value="92"/>
      <enumeration value="93"/>
      <enumeration value="94"/>
      <enumeration value="95"/>
      <enumeration value="96"/>
      <enumeration value="97"/>
      <enumeration value="98"/>
      <enumeration value="99"/>
    </restriction>
  </simpleType>
  <simpleType name="TolkningMetodeType">
    <restriction base="string">
      <enumeration value="10"/>
      <enumeration value="20"/>
      <enumeration value="30"/>
      <enumeration value="40"/>
    </restriction>
  </simpleType>
  <element name="array" substitutionGroup="gml:AbstractObject" type="grunnundersokelserutvidet:arrayType"/>
  <complexType name="arrayType">
    <sequence>
      <element maxOccurs="unbounded" minOccurs="0" name="title">
        <annotation>
          <documentation>undersOmr &gt; GeotekniskUnders-title</documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="arrayPropertyType">
    <sequence>
      <element ref="grunnundersokelserutvidet:array"/>
    </sequence>
  </complexType>
</schema>
